# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "perm_addAccountsToAllowlist",
#    "params": [
#        [
#            "0xb9b81ee349c3807e46bc71aa2632203c5b462032",
#            "0xb9b81ee349c3807e46bc71aa2632203c5b462034"
#        ]
#    ],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "perm_addAccountsToAllowlist",
  "params": [
    [
      "0xb9b81ee349c3807e46bc71aa2632203c5b462032",
      "0xb9b81ee349c3807e46bc71aa2632203c5b462034"
    ]
  ],
  "id": 1
}

###

# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "perm_addNodesToAllowlist",
#    "params": [
#        [
#            "enode://7e4ef30e9ec683f26ad76ffca5b5148fa7a6575f4cfad4eb0f52f9c3d8335f4a9b6f9e66fcc73ef95ed7a2a52784d4f372e7750ac8ae0b544309a5b391a23dd7@127.0.0.1:30303",
#            "enode://2feb33b3c6c4a8f77d84a5ce44954e83e5f163e7a65f7f7a7fec499ceb0ddd76a46ef635408c513d64c076470eac86b7f2c8ae4fcd112cb28ce82c0d64ec2c94@127.0.0.1:30304"
#        ]
#    ],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "perm_addNodesToAllowlist",
  "params": [
    [
      "enode://7e4ef30e9ec683f26ad76ffca5b5148fa7a6575f4cfad4eb0f52f9c3d8335f4a9b6f9e66fcc73ef95ed7a2a52784d4f372e7750ac8ae0b544309a5b391a23dd7@127.0.0.1:30303",
      "enode://2feb33b3c6c4a8f77d84a5ce44954e83e5f163e7a65f7f7a7fec499ceb0ddd76a46ef635408c513d64c076470eac86b7f2c8ae4fcd112cb28ce82c0d64ec2c94@127.0.0.1:30304"
    ]
  ],
  "id": 1
}

###


# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "perm_getAccountsAllowlist",
#    "params": [],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "perm_getAccountsAllowlist",
  "params": [],
  "id": 1
}

###

# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "perm_getNodesAllowlist",
#    "params": [],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "perm_getNodesAllowlist",
  "params": [],
  "id": 1
}

###


# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "perm_reloadPermissionsFromFile",
#    "params": [],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "perm_reloadPermissionsFromFile",
  "params": [],
  "id": 1
}

###

# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "perm_removeAccountsFromAllowlist",
#    "params": [
#        [
#            "0xb9b81ee349c3807e46bc71aa2632203c5b462032",
#            "0xb9b81ee349c3807e46bc71aa2632203c5b462034"
#        ]
#    ],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "perm_removeAccountsFromAllowlist",
  "params": [
    [
      "0xb9b81ee349c3807e46bc71aa2632203c5b462032",
      "0xb9b81ee349c3807e46bc71aa2632203c5b462034"
    ]
  ],
  "id": 1
}

###

# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "perm_removeNodesFromAllowlist",
#    "params": [
#        [
#            "enode://7e4ef30e9ec683f26ad76ffca5b5148fa7a6575f4cfad4eb0f52f9c3d8335f4a9b6f9e66fcc73ef95ed7a2a52784d4f372e7750ac8ae0b544309a5b391a23dd7@127.0.0.1:30303",
#            "enode://2feb33b3c6c4a8f77d84a5ce44954e83e5f163e7a65f7f7a7fec499ceb0ddd76a46ef635408c513d64c076470eac86b7f2c8ae4fcd112cb28ce82c0d64ec2c94@127.0.0.1:30304"
#        ]
#    ],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "perm_removeNodesFromAllowlist",
  "params": [
    [
      "enode://7e4ef30e9ec683f26ad76ffca5b5148fa7a6575f4cfad4eb0f52f9c3d8335f4a9b6f9e66fcc73ef95ed7a2a52784d4f372e7750ac8ae0b544309a5b391a23dd7@127.0.0.1:30303",
      "enode://2feb33b3c6c4a8f77d84a5ce44954e83e5f163e7a65f7f7a7fec499ceb0ddd76a46ef635408c513d64c076470eac86b7f2c8ae4fcd112cb28ce82c0d64ec2c94@127.0.0.1:30304"
    ]
  ],
  "id": 1
}

###











