# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "plugins_reloadPluginConfig",
#    "params": [
#        "tech.pegasys.plus.plugin.kafka.KafkaPlugin"
#    ],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "plugins_reloadPluginConfig",
  "params": [
    "tech.pegasys.plus.plugin.kafka.KafkaPlugin"
  ],
  "id": 1
}

###

