# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "txpool_besuPendingTransactions",
#    "params": [
#        2,
#        {
#            "from": {
#                "eq": "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
#            },
#            "gas": {
#                "lt": "0x5209"
#            },
#            "nonce": {
#                "gt": "0x1"
#            }
#        }
#    ],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "txpool_besuPendingTransactions",
  "params": [
    2,
    {
      "from": {
        "eq": "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
      },
      "gas": {
        "lt": "0x5209"
      },
      "nonce": {
        "gt": "0x1"
      }
    }
  ],
  "id": 1
}

###

# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "txpool_besuStatistics",
#    "params": [],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "txpool_besuStatistics",
  "params": [],
  "id": 1
}

###

# curl --location --request POST 'http://localhost:8545'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "jsonrpc": "2.0",
#    "method": "txpool_besuTransactions",
#    "params": [],
#    "id": 1
#}'
POST {{url}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "txpool_besuTransactions",
  "params": [],
  "id": 1
}

###





